# Generated by Django 4.2.7 on 2023-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=200)),
                ("major", models.CharField(default=None, max_length=200)),
                ("grade", models.CharField(default=None, max_length=10)),
                ("year_start", models.DateField(default=None)),
                ("year_end", models.DateField(default=None)),
            ],
        ),
    ]
